src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime", options={"default"="CURRENT_TIMESTAMP"})
     */
    private $date_creation;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('contenu')
            ->add('categorie')
            ->add('Envoyer', SubmitType::class );
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Article;
use App\Entity\Categorie;
use App\Form\ArticleType;
use App\Form\CategorieType;
use App\Repository\ArticleRepository; 
use App\Repository\CategorieRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article/{id<\d+>}", name="app_article")
     */
    public function index($id, ArticleRepository $articleRepo, CategorieRepository $categorieRepo): Response
    {
        $article = $articleRepo->find($id);
        return $this->render('article/index.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/articles", name="app_articles")
     */
    public function articles(ArticleRepository $articleRepo): Response
    {
        $articles = $articleRepo->findAll();
        return $this->render('article/articles.html.twig', [
            'articles' => $articles,
            
        ]);
    }

    /**
     * @Route("/articleAdd", name="add_article")
     */
    public function articleAdd(Request $request, ManagerRegistry $doctrine): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $manager = $doctrine->getManager();
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()){
            $article = $form->getData();
            $article->setDateCreation(new DateTime());
            $manager->persist($article);
            $manager->flush(); //execute les requetes de base
            return $this->redirect('article/'.$article->getId());
        }

        return $this->renderForm('article/articleAdd.html.twig', [
            'form' => $form
        ]);
    }
    /**
     * @Route("/articleDel", name="del_article")
     */
    public function articleDel(ArticleRepository $articleRepo): Response
    {
        $articles = $articleRepo->findAll();
        return $this->render('article/articlesDel.html.twig', [
            'articles' => $articles,
            
        ]);
    }

    /**
     * @Route("/articleDel/{id}", name="suppr_article")
     */
    public function supprArticle(ArticleRepository $articleRepo, $id): Response
    {
        $article = $articleRepo->find($id);
        $delArticle = $articleRepo->remove($article, true);
        return $this->redirectToRoute('del_article');
    }
}

templates/article/articleAdd.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
    <div class="main">
    <h1>Ajouter un article</h1>   
    {{form(form)}}
    </div>
{% endblock %}

templates/article/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <div class="main">
    <h1>Liste des articles</h1>
        <ul>
        {% for article in articles %}
            <li><a href="{{ path('app_article',{'id': article.id}) }}">Article: {{article.id}} - {{article.titre}} - {{article.dateCreation|date("d/m/Y H:i:s")}} </a></li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/article/articlesDel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer un article{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
    <div class="main">
        <h1>Supprimer un article</h1>
        <table>
            <thead>
                <th>Identifiant </th>
                <th>Titre</th>
                <th>Date de création</th>
                <th>catégorie</th>
            </thead>
            <tbody>
        {% for article in articles %}
            <td>{{article.getId}}</td>
            <td> {{article.getTitre}} </td>            
            <td> {{article.getDateCreation|date("d/m/Y \\à H:i:s")}} </td>
            <td> {{article.getCategorie}} </td>
            <td> <a href="{{ path('suppr_article',{'id': article.getId}) }}">Supprimer l'article</a> </td>
            <tr></tr>
            
        {% endfor %}
    </div>  
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}article{% endblock %}

{% block body %}
<style>
    body{ 
        background-image: url({{ article.categorie.fond }});
        background-size: cover;
        text-shadow: 1px 1px 2px white, 0 0 1em white, 0 0 0.2em white;
    }
</style>
<div style="text-align:center">
    <h1> {{article.titre}} </h1>
    <p> Catégorie: <a href="{{ path('app_categorie',{'id': article.categorie.id}) }}">{{article.categorie.libelle}}</a></p>
    <p> {{article.contenu|raw}} </p>
</div>
    <p style="text-align:right; padding-right:60px">Article crée le: {{article.dateCreation|date("d/m/Y \\à H:i:s")}}</p>

{% endblock %}